import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/css/globals.css";

import { FiltersProvider } from "@/lib/filters/state/FiltersContext";
import { MoviesProvider } from "@/services/sanity/movies/state/MoviesContext";
import Header from "@/components/[Header]/Header";

import { getMovies } from "@/services/sanity/movies/queries/getMovies";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 🧠 Fetch movies server-side
  const movies = await getMovies();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <FiltersProvider>
          {/* Provide Sanity data to the app */}
          <MoviesProvider initialMovies={movies}>
            <div className="min-h-screen bg-gray-950 text-white">
              <Header />
              {children}
            </div>
          </MoviesProvider>
        </FiltersProvider>
      </body>
    </html>
  );
}
